name: Remote Access via Ngrok

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: 'SSH User (e.g., runner)'
        required: true
        default: 'runner'
      ssh_port:
        description: 'SSH Port'
        required: true
        default: '22'

jobs:
  remote_access:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ngrok
        uses: ngrok/ngrok-action@v1.0.0
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          
      - name: Start Ngrok Tunnel and Display URL
        run: |
          ngrok tcp ${{ github.event.inputs.ssh_port }} --log-format=json > ngrok.log &
          
          # Wait for the tunnel to become active
          sleep 5
          
          # Use curl and jq to get the public URL from the ngrok API
          public_url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          # Extract host and port
          host=$(echo $public_url | sed 's/tcp:\/\///' | cut -d':' -f1)
          port=$(echo $public_url | sed 's/tcp:\/\///' | cut -d':' -f2)
          
          echo "Connect to your runner using:"
          echo "ssh ${{ github.event.inputs.ssh_user }}@$host -p $port"
          echo "The runner will stay active for 6 hours unless the job is canceled."

      - name: Keep job running
        run: |
          echo "Keeping job alive..."
          sleep 21600 # Wait for 6 hours (60 * 60 * 6 = 21600 seconds)
